# Site settings
title: My Book Blog
description: A blog about books
author: Chloe
email: chloesegura545@gmail.com
url: https://c-hloe87.github.io/book

# Build settings
theme: slate 
markdown: kramdown
plugins:
  - jekyll-feed

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
